In [1]:
import numpy as np

In [2]:
A = np.matrix([[50,40],[10,10]]) 
B = np.matrix([[30,100],[20,15]])
A+B

matrix([[ 80, 140],
        [ 30,  25]])

In [3]:
A * 0.8

matrix([[40., 32.],
        [ 8.,  8.]])

In [4]:
A * B

matrix([[2300, 5600],
        [ 500, 1150]])

In [8]:
A = np.matrix([[1,3],[2,1]]) #2*2
B = np.matrix([[145],[72]]) #2*1

A*B

matrix([[361],
        [362]])

In [9]:
1 * 145 + 3 * 72

361

In [10]:
2 * 145 + 1 * 72

362

In [14]:
# 逆行列
A = np.matrix([[5,3],[2,1]])
B = np.linalg.inv(A)
B

matrix([[-1.,  3.],
        [ 2., -5.]])

In [19]:
(A * B).astype(int) 

matrix([[1, 0],
        [0, 1]])

In [21]:
A = np.matrix([[5,3],[2,1]])
inv_A = np.linalg.inv(A)
B = np.matrix([[9],[4]])
inv_A * B

matrix([[ 3.],
        [-2.]])